# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import requests
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import load_model
import numpy as np
import pandas as pd
import tensorflow as tf
from flask import Flask, request, render_template, redirect, url_for
import os
from tensorflow.python.keras.backend import set_session

from flask import Flask
from flask_ngrok import run_with_ngrok
app = Flask(__name__)
run_with_ngrok(app)   
# load both the vegetable and fruit models.
model = load_model("/content/drive/MyDrive/Plant Diseases/Ibm Training Files/vegetable.h5")
model1 = load_model("/content/drive/MyDrive/Plant Diseases/Ibm Training Files/fruit.h5")
#home page
@ app.route('/')
def home():
    return render_template('home1.html')

# prediction page.
@ app.route('/prediction')
def prediction():
    return render_template('predict.html')
@ app.route('/predict',methods=['post'])
def predict():
    if request.method =='post':
       # get the file from post request
       f = request.files['image']
       # save the files to ./uploads
       basepath = os.path.dirname(_file_)
       file_path = os.path.join(basepath,'uploads', secure_filename(f.filename))
       f.save(file_path)
       img=image.load_img(file_path,target_size=(120,120))
       x=image.imgtoarray(img)
       x=np.expand_dims(x,axis=0)
       plant= request.form['plant']
       print(plant)
       if(plant =="vegetable"):
            preds = model.predict_classes(x)
            print (preds)
            df = pd.read_excel('precautions -veg.xlsx')
       print(df.iloc[preds[0]]['caution'])
    else :
            preds = model1.predict_classes(x)
            df =pd.read_excel('precautions -fruits.xlsx')
            print(df.iloc[preds[0]]['caution'])
    return df.iloc[preds[0]]['caution']

if __name__ == "__main__":
    app.run()